-------BTTHUCHANH
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20)

ALTER TABLE KHACHHANG
ADD LOAIKH TINNYINT

ALTER TABLE SANPHAM
ALTER COLUMN VARCHAR(100)

ALTER TABLE SANPHAM
DROP COLUMN GICHU

ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(20)

ALTER TABLE SANPHAM  
ADD CONSTRAINT SANPHAM_DVT CHECK (DVT = 'cay' OR DVT = 'hop' OR DVT = 'cai' OR DVT = 'quyen' OR DVT = 'chuc')



