-------BTTHUCHANH
--BAI2
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20)


--BAI3
ALTER TABLE KHACHHANG
ADD LOAIKH TINNYINT

--BAI4
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100)


--BAI5
ALTER TABLE SANPHAM
DROP COLUMN GHICHU

--BAI6
ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(20)

--BAI7
ALTER TABLE SANPHAM  
ADD CONSTRAINT SANPHAM_DVT CHECK (DVT = 'cay' OR DVT = 'hop' OR DVT = 'cai' OR DVT = 'quyen' OR DVT = 'chuc')

--BAI8
ALTER TABLE SANPHAM
ADD CONSTRAINT SANPHAM_GIA CHECK(GIA > 500)

--BAI9


--BAI10
ALTER TABLE KHACHHANG ADD CONSTRAINT CHECK_NGDK CHECK (NGDK>NGSINH)

--BAI11
CREATE TRIGGER UPDATE_KH_C11
ON KHACHHANG
FOR UPDATE
AS
 DECLARE @NGDK SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGDK=NGDK
 FROM  INSERTED
 
 IF(@NGDK>ANY(SELECT NGHD
    FROM  HOADON A, INSERTED I
    WHERE A.MAKH=I.MAKH))
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!NGDK PHAI NHO HON NGHD'
  END
 ELSE
  PRINT' SUCCESSFUL'
 -------
CREATE TRIGGER HD_C11
ON HOADON
FOR INSERT,UPDATE
AS
 DECLARE @NGDK SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGDK=NGDK,@NGHD=NGHD
 FROM  INSERTED I, KHACHHANG A
 WHERE I.MAKH=A.MAKH

 IF @NGHD<@NGDK
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!NGHD PHAI LON HON NGDK'
  END
 ELSE
  PRINT' SUCCESSFUL'

  --BAI12

  CREATE TRIGGER UPDATE_NV_C12
ON NHANVIEN
FOR UPDATE
AS
 DECLARE @NGVL SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGVL=NGVL
 FROM  INSERTED
 
 IF(@NGVL>ANY(SELECT NGHD
    FROM  HOADON A, INSERTED I
    WHERE A.MANV=I.MANV))
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!NGVL PHAI NHO HON NGHD'
  END
 ELSE
  PRINT' SUCCESSFUL'
 -------
CREATE TRIGGER HD_C12
ON HOADON
FOR INSERT,UPDATE
AS
 DECLARE @NGVL SMALLDATETIME, 
   @NGHD SMALLDATETIME

 SELECT @NGVL=NGVL,@NGHD=NGHD
 FROM  INSERTED I, NHANVIEN A
 WHERE I.MANV=A.MANV

 IF @NGHD<@NGVL
  BEGIN
   ROLLBACK TRAN
   PRINT 'ERROR!NGHD PHAI LON HON NGVL'
  END
 ELSE
  PRINT' SUCCESSFUL'
/*CAU 13*/
CREATE TRIGGER CTHD_C13
ON CTHD
FOR DELETE,UPDATE
AS
 DECLARE @SL  INT,
   @SOHD INT

 SELECT @SL=COUNT(A.SOHD),@SOHD=D.SOHD
 FROM  DELETED D,CTHD A
 WHERE A.SOHD=D.SOHD
 GROUP BY  D.SOHD

 IF(@SL<1)
  BEGIN
   DELETE FROM HOADON
   WHERE  SOHD=@SOHD
   PRINT 'DA DELETE CTHD CUOI CUNG CUA HOADON TREN'
  END 

 
  --BAI13
CREATE TRIGGER HOADON_C13
ON HOADON
FOR INSERT
AS
 DECLARE @SOHD INT

 SELECT @SOHD=SOHD
 FROM  INSERTED
 
 UPDATE CTHD
 SET  MASP='NONE',SL=0
 WHERE SOHD=@SOHD

 PRINT 'SUCCESSFUL! DE NGHI UPDATE LAI CTHD(MAC DINH:MASP="NONE", SL=0)'

 --BAI14
CREATE TRIGGER INSERT_HOADON_C14
ON HOADON
FOR INSERT
AS
 UPDATE HOADON
 SET  TRIGIA=0
 WHERE SOHD=(SELECT  SOHD
    FROM  INSERTED)
 PRINT'DA INSERT 1 HOADON VOI TRIGIA BAN DAU LA 0 VND' 
 -------------
CREATE TRIGGER UPDATE_HOADON_C14
ON HOADON
FOR INSERT
AS
 UPDATE HOADON
 SET  TRIGIA=(SELECT TRIGIA
     FROM DELETED)
 WHERE SOHD=(SELECT  SOHD
    FROM  INSERTED)
 PRINT'DA UPDATE 1 HOADON VOI TRIGIA KHONG THAY DOI'
 -------------
CREATE TRIGGER INSERT_CTHD_C14
ON CTHD
FOR INSERT
AS
 DECLARE  @SL  INT,
   @GIA  MONEY,
   @SOHD INT

 SELECT @GIA=GIA,@SL=SL,@SOHD=SOHD
 FROM  INSERTED A, SANPHAM B
 WHERE A.MASP=B.MASP

 UPDATE HOADON
 SET  TRIGIA=TRIGIA+@SL*@GIA
  PRINT'DA INSERT 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
 --------------
CREATE TRIGGER DELETE_CTHD_C14
ON CTHD
FOR DELETE
AS
 DECLARE  @SL  INT,
   @GIA  MONEY,
   @SOHD INT

 SELECT @GIA=GIA,@SL=SL,@SOHD=SOHD
 FROM  DELETED A, SANPHAM B
 WHERE A.MASP=B.MASP

 UPDATE HOADON
 SET  TRIGIA=TRIGIA-@SL*@GIA
  PRINT'DA DELETE 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
 -------------------
CREATE TRIGGER UPDATE_CTHD_C14
ON CTHD
FOR UPDATE
AS
 DECLARE  @SL_CU INT,
   @SL_MOI INT,   
   @GIA_CU MONEY,
   @GIA_MOI MONEY,
   @SOHD_CU INT,
   @SOHD_MOI INT

 SELECT @GIA_CU=GIA,@SL_CU=SL,@SOHD_CU=SOHD
 FROM  DELETED A, SANPHAM B
 WHERE A.MASP=B.MASP
 
 SELECT @GIA_MOI=GIA,@SL_MOI=SL,@SOHD_MOI=SOHD
 FROM  INSERTED A, SANPHAM B
 WHERE A.MASP=B.MASP

 IF(@SOHD_CU=@SOHD_MOI)
  BEGIN
   UPDATE HOADON
   SET  TRIGIA=TRIGIA+@SL_MOI*@GIA_MOI-@SL_CU*@GIA_CU
   WHERE SOHD=@SOHD_CU
  END
 ELSE
  BEGIN
   UPDATE HOADON
   SET  TRIGIA=TRIGIA-@SL_CU*@GIA_CU
   WHERE SOHD=@SOHD_CU

   UPDATE HOADON
   SET  TRIGIA=TRIGIA+@SL_MOI*@GIA_MOI
   WHERE SOHD=@SOHD_MOI
  END
 PRINT'DA UPDATE 1 CTHD VA UPDATE LAI TRIGIA CUA HOADON TUONG UNG'
 -------------------
CREATE TRIGGER UPDATE_HOADON_C14
ON  HOADON
FOR  INSERT
AS
 DECLARE @GIA_CU MONEY,
   @GIA_MOI MONEY,
   @SOHD INT,
   @SL  INT
   
 SELECT @GIA_CU=GIA
 FROM  DELETED
 SELECT @GIA_MOI=GIA
 FROM  INSERTED

 SELECT @SOHD=SOHD,@SL=SL
 FROM  INSERTED A, CTHD B
 WHERE A.MASP=B.MASP

 UPDATE HOADON
 SET  TRIGIA=TRIGIA+@SL*(@GIA_MOI-@GIA_CU) 
 WHERE SOHD=@SOHD
  PRINT'DA UPDATE 1 HOADON VOI TRIGIA KHONG THAY DOI'

  --BAI15
CREATE TRIGGER INSERT_KHACHHANG_C15
ON KHACHHANG
FOR INSERT
AS
 DECLARE @MAKH CHAR(4)

 SELECT @MAKH=MAKH
 FROM  INSERTED
 
 UPDATE KHACHHANG
 SET  DOANHSO=0
 WHERE MAKH=@MAKH

 PRINT 'DA INSERT 1 KHACHHANG MOI VOI DOANHSO BAN DAU LA 0 VND'
 ----------------
CREATE TRIGGER UPDATE_KHACHHANG_C15
ON KHACHHANG
FOR UPDATE
AS
 DECLARE @MAKH  CHAR(4),
   @DOANHSO_CU MONEY

 SELECT @MAKH=MAKH
 FROM  INSERTED
 
 SELECT @DOANHSO_CU=DOANHSO
 FROM  DELETED
 
 UPDATE KHACHHANG
 SET  DOANHSO=@DOANHSO_CU
 WHERE MAKH=@MAKH

 PRINT 'DA UPDATE 1 KHACHHANG'
 ----------------
CREATE TRIGGER INSERT_HOADON_C15
ON HOADON
FOR INSERT
AS
 DECLARE @TRIGIA MONEY,
   @MAKH CHAR(4)

 SELECT @MAKH=MAKH,@TRIGIA=TRIGIA
 FROM  INSERTED
 
 UPDATE KHACHHANG
 SET  DOANHSO=DOANHSO+@TRIGIA
 WHERE MAKH=@MAKH

 PRINT 'DA INSERT 1 HODON MOI VA UPDATE LAI DOANHSO CUA KH CO SOHD TREN'

 -----------
CREATE TRIGGER DELETE_HOADON_C15
ON HOADON
FOR DELETE
AS
 DECLARE @TRIGIA MONEY,
   @MAKH CHAR(4)

 SELECT @MAKH=MAKH,@TRIGIA=TRIGIA
 FROM  DELETED
 
 UPDATE KHACHHANG
 SET  DOANHSO=DOANHSO-@TRIGIA
 WHERE MAKH=@MAKH

 PRINT 'DA DELETE 1 HODON MOI VA UPDATE LAI DOANHSO CUA KH CO SOHD TREN'
 ---------------
CREATE TRIGGER UPDATE_HOADON_C15
ON HOADON
FOR UPDATE
AS
 DECLARE @TRIGIA_CU MONEY,
   @TRIGIA_MOI MONEY,
   @MAKH  CHAR(4)

 SELECT @MAKH=MAKH,@TRIGIA_MOI=TRIGIA
 FROM  INSERTED

 SELECT @MAKH=MAKH,@TRIGIA_CU=TRIGIA
 FROM  DELETED
  
 UPDATE KHACHHANG
 SET  DOANHSO=DOANHSO+@TRIGIA_MOI-@TRIGIA_CU
 WHERE MAKH=@MAKH

 PRINT 'DA UPDATE 1 HOADON MOI VA UPDATE LAI DOANHSO CUA KH CO SOHD TREN'